### ISSUE TITLE
Why are you recreating https://en.wikipedia.org/wiki/Yellow_badge

### ISSUE THREAD

**Issue by Wazubaba** [sticks-stuff/highlight-RMS-supporters#26]
As the topic says, since I know you'll just delete it anyways.

Sincerely: Proud member of your future purge list #3500

**Comment by simonsan** [comment]
Please read https://github.com/sticks-stuff/highlight-RMS-supporters/issues/3 .

Although you might be baffled that you are on the list, you should stay calm and thoughtful.

**Comment by Wazubaba** [comment]
You are telling me to be more thoughtful when you are literally trying to create a modern-day equivalent to the Jude star. Think about that for a moment. And believe me, I am as calm as can be. In fact, I'm kind of enjoying seeing you sorts out yourselves as the facists you always were.

**Comment by simonsan** [comment]
> You are telling me to be more thoughtful when you are literally trying to create a modern-day equivalent to the Jude star. Think about that for a moment. And believe me, I am as calm as can be. In fact, I'm kind of enjoying seeing you sorts out yourselves as the facists you always were.

I don't think you are right in any way here. It's about highlighting the enablers and supporters. As you can see, the aggressive side, that freaks out on 4chan/8chan/GAB or how all that bullshit is called, because they feel wrongly oppressed. If you already want to compare it to fascists, it's more like: "giving the supporters of the fascist party (the list of RMS supporters) an armlet to recognize them better on the street." while fighting them where ever you can. So, yeah. Hopefully you understand the comparison. :)

**Comment by rlyriley** [comment]
Dear GitHub user Wazubaba, there is a difference between being marked for opinions and being marked for being Jewish. This will not impact your life at all, as there are no repercussions past your name becoming red.

Furthermore, I do not believe RMS is your lord and savior, nor does this discriminate against you because of your ethnicity, so you are not getting discriminated against for being a part of an ethnoreligious group either. Hope you understand the differences!

**Comment by simonsan** [comment]
P.S.: 
![sticker](https://user-images.githubusercontent.com/14062932/112799808-24e9be00-906f-11eb-84f1-260fe64312a3.jpg)

**Comment by Wazubaba** [comment]
You people are insane. RMS is literally anti-nazi. What the hell is wrong with you all?
Furthermore, this is clearly intended to damage people's possible job prospects with a targeted shaming campaign. Don't try to play some stupid game here. **You are marking people for having a different ideology to you.** There is absolutely no difference to what you are doing here and what the nazis did. You have gazed too long into the abyss here and become the very monsters you hate. Wake up.

Also what on earth does this have to do with the patriarchy? This is about foss. Why are you dragging something completely off-topic into this?

**Comment by simonsan** [comment]
Could it be, that you haven't read the letter to remove RMS? 
https://rms-open-letter.github.io/

I cite: "He has shown himself to be misogynist, ableist, and transphobic, among other serious accusations of impropriety."

Why are you supporting and enabling such a person and if so, why can't you/don't want to understand that other people don't want to have anything to do with such persons and their supporters?

**Comment by Wazubaba** [comment]
Because as shocking as it is I am capable of coming to my own conclusions and don't just immediately jump on a bandwagon when I see it. On top of that, the requirements to have those terms thrown at you change every other month. I don't subscribe to your stupid politics, I just focus on software. I don't give a single damn what someone says short of if it is going to lead to actual harm. I see an attack on foss as a hell of a lot more important than random people's feelings being hurt. All I see here are a bunch of bullies on the internet picking on a dude who is old, has some disabilities, and has contributed more to the world than any of them ever will in their entire lives. Without RMS there would be no foss. I don't want to have to get involved with the crazy people of this world I just want to see foss, about the only good thing left in the entire computing community, not be destroyed over stupid childish "he said she said" drama. And now I and thousands of other people are being stigmatized for the mere act of disagreeing with you. You are all rapidly becoming the monsters you claim to hate. That you cannot see that is simultaneously hilarious and mortally terrifying.

And I am still waiting to find out what sort of word salad will be used to explain what exactly the patriarchy has to do with any of this.

**Comment by simonsan** [comment]
I see, that your inner fears turn inside out. Yes, I understand that the world might run faster these days, you don't need to feel left behind. FOSS is great, that doesn't mean all the people doing it are great, too. Some of them show behaviour, that others don't accept. 

Imho you should really ask yourself why you make it so easy for yourself and rather support people in power that are showing bad behaviour over others. Where does this come from, isn't that itself ideologue? To support someone doing wrong just because you like what the person did elsewhere? Isn't that biased? How do you feel within this?

**Comment by WlarusFromDaSpace** [comment]
![image](https://user-images.githubusercontent.com/44726328/112802857-5d8f9480-907b-11eb-962f-fed5021e9d13.png)
It isn't as much recreating the yellow badge as much as it is recreating the red triangle.
Even though it isn't as fitting of a comparison as it was only used in the camps.

**Comment by Wazubaba** [comment]
@simonsan
> I see, that your inner fears turn inside out. Yes, I understand that the world might run faster these days, you don't need to feel left behind. FOSS is great, that doesn't mean all the people doing it are great, too. Some of them show behaviour, that others don't accept.
> 
> Imho you should really ask yourself why you make it so easy for yourself and rather support people in power that are showing bad behaviour over others. Where does this come from, isn't that itself ideologue? To support someone doing wrong just because you like what the person did elsewhere? Isn't that biased? How do you feel within this?

Why are you talking like some kind of movie character? He hasn't directly done a single thing wrong. It wasn't his intent to offend, merely to offer his own opinion. Anyone who is offended by the things he says has nobody but themselves to blame for being incapable of hearing a different viewpoint than their own. I disagree with lots of things he says, doesn't mean I want to see his life destroyed over it because I'm not a facist. If that's a bad behavior to you then you should seriously re-evaluate your life.

@WlarusFromDaSpace
Perhaps, I would need to do more research on the subject but it still amounts to the same thing regardless - this is a branding of heretics - an attack to try to shame and silence people.

(I'm hoping I did the names right because I'm not used to github issues not being instantly deleted)

**Comment by simonsan** [comment]
> It isn't as much recreating the yellow badge as much as it is recreating the red triangle.
> Even though it isn't as fitting of a comparison as it was only used in the camps.

I always ask myself, if this is not really embarrassing somehow. You compare things that are completely unrelated just to victimize yourself as all these funny Trumpletons did. And you seem to really believe that. I find that kinda funny as well. You have nothing to do with discriminated people, you can repeat it everyday in your right-wing bubble, but it doesn't get more true because of this. :D

**Comment by Wazubaba** [comment]
@simonsan Why are you bringing trump into this now? You aren't discriminated against because someone has a different opinion than you either. How is not acting like this is the salem witch trials over someone having a different opinion than you right-wing?

So let's get this straight, Somehow, RMS having a different opinion than you, the patriarchy, trump, right wing stuff, and people on random websites is why you feel it is necessary to try to attack several thousand people for disagreeing with you? Am I right?

How in the world is that any different than what the nazi's did? Is it just because the scale is off?

**Comment by WlarusFromDaSpace** [comment]
@simonsan
Hey no need to get aggressive.
I haven't even signed either letter, I just was reading these issues as they are entertaining and noticed that the red triangle fit better than the yellow badge.
>inb4 4chan

I come from leftypol, 4chan hates me :)

**Comment by simonsan** [comment]
> Why are you talking like some kind of movie character? He hasn't directly done a single thing wrong. It wasn't his intent to offend, merely to offer his own opinion. Anyone who is offended by the things he says has nobody but themselves to blame for being incapable of hearing a different viewpoint than their own. I disagree with lots of things he says, doesn't mean I want to see his life destroyed over it because I'm not a facist. If that's a bad behavior to you then you should seriously re-evaluate your life.

I think you should really think about that if someone says something that he disguises as his own opinion and that is offending others. Ask yourself why is it fine for you in the first place to offend others, how less respect do you have for others, that you think it's a valid thing to do? How much pain and disrespect by others must you have gone through in your life to think it's a right to offend others?

Regarding:
`Anyone who is offended by the things he says has nobody but themselves to blame for being incapable of hearing a different viewpoint than their own.`
