### ISSUE TITLE
This script is discriminatory

### ISSUE THREAD

**Issue by xerydian** [sticks-stuff/highlight-RMS-supporters#3]

**Comment by xerydian** [comment]
Please delete it 😃

**Comment by simonsan** [comment]
Could you explain why?

**Comment by xerydian** [comment]
@simonsan Yes, i can.

[Definition of discrimination, Cambridge dictionary:](https://dictionary.cambridge.org/amp/english/discrimination)
Treating a person or particular group of people differently, especially in a worse way from the way in which you treat other people, because of their skin colour, sex, sexuality, etc.

**The default GitHub behavior:** every user is displayed in the same way.

**What this script does:** displays some users with a different color, because of their personal beliefs, and enables people to target them more easily. Having a big red target following your name wherever you go is demeaning and can potentially make people more susceptible to attacks.

**Comment by simonsan** [comment]
Hmm, the way I see it this is more for highlighting people you don't want to have anything to do with because of their beliefs. It's fine to read them somewhere in a repository, but you want to be aware, that you will never be friends with them or that you don't let them in your private space. While I understand that you think it's like a big target on their back I'm trying to explain to you that for me it's the opposite really. I want to actively ignore them.

**Comment by simonsan** [comment]
Furthermore, if I read this open letter right <https://rms-open-letter.github.io/> I hope it's understandable from a certain viewpoint, that you don't want to have anything to do with enablers and supporters of such a person. And that should be actually fine, also to make it easier for others to do the same.

Imho you also use the word discriminatory wrongly here, because that is a principle of power and follows a power imbalance. RMS and his supporters can't be discriminated because they are in the position of power. Fighting back against that is not discriminatory behaviour, but just self-help against patriarchy.

**Comment by xerydian** [comment]
I see where you're coming from but I still think this is not the right solution. With minimal tweaks, someone could fork this script and turn it into a script that highlights people who signed the open letter, or that highlights people who are jewish, or LGBT. And that is because this script is fundamentally discriminatory -regardless of the dataset.

I respect you do not want to talk to people you disagree with, but creating a feature that categorizes users into "the good users" and "the bad ones" only lends itself to division, fights, and tribalism.

**Comment by simonsan** [comment]
> I see where you're coming from but I still think this is not the right solution. With minimal tweaks, someone could fork this script and turn it into a script that highlights people who signed the open letter, or that highlights people who are jewish, or LGBT. And that is because this script is fundamentally discriminatory -regardless of the dataset.

But the point is, that this script doesn't highlight people that are suffering from antisemitism, sexism, xenophobia or anything else in that regards. It highlights people that are enabling these things, as I tried to explain before. The argument, that this script can be used with minimal tweaks for something bad is imho a spurious argument, given the context and how easy it is to do something like that, while this one is not really damaging anything/anyone.

> I respect you do not want to talk to people you disagree with, but creating a feature that categorizes users into "the good users" and "the bad ones" only lends itself to division, fights, and tribalism.

I don't necessarily think that the signers of the letter are in general evil or bad. I don't know these people. I think some of them might be really not reflective of the situation, some may be ignorant, some may be straight out misogynists themselves. But given the fact, that they feel they need to show their support for such behaviour, instead of getting in contact with the persons that signed the letter, getting more information about the situation etc. just shows me, that these are not really persons you want to deal with, and if that is divisionist, so be it. People are there to talk, these people were going to the public to talk about a problem inside the community. Talk with them, ask them questions, how do they feel, what were they going through. But please don't argument within the old ways of people that don't want to lose their power.

**Comment by Technoturnovers** [comment]
you do realize that rms-open-letter closed their issue tracker, are only accepting private email signatures, and have refused to change factually wrong information while allowing additions of more allegations, right?

**Comment by sticks-stuff** [comment]
Hi, please keep issues related to the implantation of this project and not about whether it should be implemented. Those who want to remove their names from this repo may remove their names from https://github.com/rms-support-letter/rms-support-letter.github.io and the bot will also remove your name from here :)

**Comment by RaphyJake** [comment]
@simonsan 
> I think some of them might be really not reflective of the situation, some may be ignorant, some may be straight out misogynists themselves

Are you reflective of the situation? https://sterling-archermedes.github.io/ here's a very thorough rundown of all the accusations Stallman was facing in 2019, together with all the sources. I'm sure you can find some time to read it, being the open mind person that you are.

Regardless of whenever Stallman might have views I dislike or not, he is by no means discriminatory, and I am by no means discriminatory. And even if the open letter supporting Stallman is very appealing, admittedly, to right wingers and whoever dislikes the left, because the-enemy-of-my-enemy-is-my-friend, there is one problem that you failed to address completely: 

Do you really want to live in a world where if a bunch of journalists take of you of context, 3000~ people can gather up and decide that you have to lose your job? I'm sure you're aware of the term "witch-hunting" and "cancel culture", and I'm sure you realize that these pose a threat to freedom of speech and thought. If Stallman did any harm to anyone, then you should definitely warn competent authorities of the matter.

> Imho you also use the word discriminatory wrongly here, because that is a principle of power and follows a power imbalance. RMS and his supporters can't be discriminated because they are in the position of power. Fighting back against that is not discriminatory behaviour, but just self-help against patriarchy.

I have no idea what you're talking about here. Surely, if you feel like you're being discriminated, it's not a good idea to solicit angry mobs at "the bad people I don't agree with!". It's very effective admittedly, but as others pointed out, that's the same thing that oppressive regimes, and "very bad guys" did. It seems to me (though, this is only my opinion) that Stallman is currently NOT in a position of power, being targeted by a large amount of people and wrongly accused of things he didn't do.

>People are there to talk

as @Technoturnovers said. If you can find a way to contact them, then please tell me! 


@sticks-stuff 

>Hi, please keep issues related to the implantation of this project and not about whether it should be implemented.
>Those who want to remove their names from this repo may remove their names from https://github.com/rms-support-letter/rms-support-letter.github.io and the bot will also remove your name from here :)

Please, all Manhattan project scientists! Let's stop talking about the ethical implications of the whole ordeal. If they don't want to be nuked, they can just leave Japan! 

as @Crazily said,  "If the jews didn't want to be gassed to death they could just not be jewish."


Personally, I don't really mind being on this list. I don't want to call you X or Y, I hope I'm being civil enough and I just want to get this point across:

"Here is a curated list of "people with X opinion (We're not sure. But we _THINK_ they believe X.)". It's not discriminatory, yes we just use it to instantly identify people by their opinion, but just to avoid them or do whatnot. If they don't want to be part of it, they can just change opinion!"

Is this what you stand for?

**Comment by M-i-k-o-t-o** [comment]
@simonsan
> Furthermore, if I read this open letter right https://rms-open-letter.github.io/ I hope it's understandable from a certain viewpoint, that you don't want to have anything to do with enablers and supporters of such a person.

Hi, the open letter is filled with lies, please see [this](https://raw.githubusercontent.com/M-i-k-o-t-o/rms-open-letter.github.io-removed-issues/main/Screenshot_2021-03-24%20Improve%20the%20appendix%20%C2%B7%20Issue%20%23951%20%C2%B7%20rms-open-letter%20rms-open-letter%20github%20io(3).png)

**Comment by robbyoconnor** [comment]
The people who signed the open letter calling for RMS to resign did so because they had experienced his bullshit from long before you were even born. Sit down, little boy.

**Comment by xerydian** [comment]
> little boy

Do not misgender her, you bigot

**Comment by M-i-k-o-t-o** [comment]
@robbyoconnor I sure love having to deal with transmisia first thing in the morning. Sigh...

Kinda funny how you list your own pronouns in your page but do not respect mine.

**Comment by M-i-k-o-t-o** [comment]
@robbyoconnor It would be better if you just admitted your mistake and apologized instead of deleting your [post](https://i.imgur.com/Pg3saMm.png) and pretend that nothing happened. Now it looks as if I am talking to myself.

**Comment by robbyoconnor** [comment]
Sorry about that.

**Comment by simonsan** [comment]
Trolls be trolling. 🤷🏽

**Comment by ghost** [comment]
Reported this repository for being discriminatory.

**Comment by robbyoconnor** [comment]
@Rhdrmhdrvf good for you. Won't get it taken down but good for you.
