### ISSUE TITLE
Inclusivity problem

### ISSUE THREAD

**Issue by Sudo-Gren** [sticks-stuff/highlight-RMS-supporters#33]
I have seen that you've put me in the blacklist: this is a huge offence towards black community that surely wouldn't be represented by racist people such you who have put a file with the n word inside this repo.

**Comment by ghost** [comment]
This repository iz oppressive in regards o' black homies so I kindly ax you ta close it otherwise I will pursue legal action against yo' persona. and shit.

In all seriousness, don't you think that by doing this you are essentially being non inclusive towards people that have a different opinion than you? @sticks-stuff

**Comment by ghost** [comment]
And I would like to add something in regards of this whole repo: you know that you are violating the GDPR by posting account details of the people that have firmed the support letter for Richard Stallman without their explicit permission, right? (Evidenced by #34) @sticks-stuff
