### ISSUE TITLE
 This repository violates the GDPR in Europe

### ISSUE THREAD

**Issue by andrew-ld** [sticks-stuff/highlight-RMS-supporters#35]
Article 4(11) of the General Data Protection Regulation (EU) 2016/679 (GDPR) requires consent to be opt-in:

"Any freely given, specific, informed and unambiguous indication of his or her wishes by which the data subject, either by a statement or by a clear affirmative action, signifies agreement to personal data relating to them being processed; [...] Silence, pre-ticked boxes or inactivity should therefore not constitute consent."

If the repository will not comply with the above mentioned law I will have to take legal action.

**Comment by MarcoBuster** [comment]
@sticks-stuff you can't keep ignoring these issues. We are serious, we will take legal action if you don't immediately comply with the GDPR law.

**Comment by Bale001** [comment]
This repo is mirroring the data from [here](https://github.com/rms-support-letter/rms-support-letter.github.io/tree/master/_data/signed). If you want your data removed from here, remove it from there.

**Comment by cordelia04m** [comment]
@EmperorBale No. This problem is this repo. Are you saying that I  should give up my freedom of thought to not have my name on this repo?

**Comment by robbyoconnor** [comment]
@andrew-ld your information is pulled from the support letter. The people supporting RMS haven't been alive long enough or never met RMS. Sit down, little boy.

**Comment by Jan200101** [comment]
@robbyoconnor are you really trying to gatekeep based on age?

**Comment by robbyoconnor** [comment]
Oh, suddenly you care about making a welcoming environment @Jan200101? So cute. I'd take your opinion into account if only you didn't simultaneously support a man who made a space unwelcoming.

**Comment by robbyoconnor** [comment]
I really love this userscript -- helps me to see the hypocrites. If you want to call out people, maybe don't be a hypocrite.

**Comment by Jan200101** [comment]
You said anything about a welcoming environment? You are antognozing be based on the color a script gives me without sound or reason
for all you know someone could have put my github url in without my permission

But no what I am actually talking about is that you are willing to disregards someones statement based on age which is really as close minded as you can get because age does not equal experience or knowledge.

But let me discriminate against you on the same grounds:
I am not going to take the opinion of someone willing to sign a letter that knowling included outright slander and inaccuracies that the writes of that letter were unwilling to fix.
Your crusade against RMS seems not to be based on morals but on the importance of the position he holds

**Comment by robbyoconnor** [comment]
@Jan200101 look at the letter, I never signed it.

**Comment by robbyoconnor** [comment]
@cordelia04m You opted in when you added your information to the rms-support-letter repo. If you don't want to be included here, remove your name from that repo and it won't show up here.

**Comment by robbyoconnor** [comment]
@cordelia04m This isn't storing any information, but rather pulling the information straight from the rms-support-letter repo. If someone doesn't want to be included, they shouldn't sign the letter. Free Speech doesn't apply since none of us are government entities. Welcome to the flip side, you are not free to say what you want without consequence.

**Comment by Jan200101** [comment]
I am glad you removed those comments Robby, they were nothing but distasteful and hurtful to the conversation.
