### ISSUE TITLE
Add option to highlight all Jew-owned repositories

### ISSUE THREAD

**Issue by owwk** [sticks-stuff/highlight-RMS-supporters#40]
@simonsan gave a perfect justification for this existence of this repo [here](https://github.com/sticks-stuff/highlight-RMS-supporters/issues/3#issuecomment-808931281):

>Hmm, the way I see it this is more for highlighting people you don't want to have anything to do with because of their beliefs. It's fine to read them somewhere in a repository, but you want to be aware, that you will never be friends with them or that you don't let them in your private space. While I understand that you think it's like a big target on their back I'm trying to explain to you that for me it's the opposite really. I want to actively ignore them.

This seems perfectly reasonable to me, but I have a suggestion.

Please can you also add the option for me to flag all repositories owned by Jews. I don't want to have anything to do with these people due to their belief in the Jewish faith. I will never be friends with these people, and I don't want to let Jews into my private space. Nothing personal, just because I find their views repulsive.

Many thanks

**Comment by Svanto24** [comment]
I'm surprised you closed this issue. I mean, your entire grievance is judging a man unfitting to what you want to reform into an ethnopolitical clique, for saying awkard but ultimately harmless things, clearly symptomatic of his autism spectrum disorder, things that have been wildly misrepresented in order to destroy the legacy of a life this ASD-suffering, jewish man for reasons that are agressively ableist.

When is your "Aktion T4" repo coming out, sticks?
